### ISSUE TITLE
Allow queries that pass in lat, lng such as done in mapit. 

### ISSUE THREAD

**Issue by kngako** [Code4SA/who-are-you-voting-for#3]
This issue is similar to #1 but it also opens up the advantages you guys have with map it, for this specific app. 

I worked on an Android app that uses Google Places, to get a persons address. It also provides the lat lng values of that specific. 

I ran some queries on mapIt with the latLng values and it returned quite accurate ward numbers which can then be mapped in the who are you voting for data.json file more easier...

You can check out some of the Android code on  https://github.com/kngako/code4sa_ward_candidates_android

**Comment by longhotsummer** [comment]
I believe this is now done, since the browser location button uses it?

**Comment by adieyal** [comment]
Yes, i think so

**Comment by kngako** [comment]
Yep, nicely done too.
